export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const INCREMENTED_ITEM = 'INCREMENTED_ITEM';
export const DECREMENTED_ITEM = 'DECREMENTED_ITEM';